name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: sahayogeshwaran # Replace with your GitHub username
          outputs: dist/snake.svg

      # Upload the result to the output branch
      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
